logging:
  level:
    org.springframework:
       security: DEBUG
server:
   port: 9999
# Domino OAuth2 Authorization Server
oauth2:
   resource:
      checkToken.url: http://localhost:8080/oauth/check_token
      clientId: spring-security-oauth2-read-client
      secret: spring-security-oauth2-read-client-password1234
