server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: auth-server
  datasource:
    #数据库连接属性
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acessos?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        #配置了实体类维护数据库表结构的具体行为, update 表示当实体类的属性发生变化时, 表结构跟着更新.使用 create 可以进行删库操作,慎用
        ddl-auto: update
      show-sql: true
      database: mysql
      properties:
           hibernate:
               format_sql: true
logging:
  #指定日志配置文件路径(ps: 有一个很神奇的东西,当你的配置文件名字默认是logback-spring.xml, 并且在 resource 目录下, 这个地方可以不写, 可以自动找到)
  config: classpath:config/logback-spring.xml


#自定义属性
#邮件开关
mail:
   enable: 1
   
# mybatis
mybatis:
     type-aliases-package: com.ywsoftware.oa.authServer.mybatis.pojo
     mapper-locations: classpath:mapper/*.xml